###

# Requisição válida (original)
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: cabeçalho não menciona formato
POST https://api.arc20201.boidacarapreta.cc/gravar
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: JSON com formato errado
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]

###

# Requisição inválida: falta 'medida'
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: 'medida' com formato errado
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": 120,
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição inválida: falta 'valores'
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ]
}

###

# Requisição inválida: 'valores' com formato errado
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": 4567
}

###

# Requisição inválida: lista 'valores' vazia
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
    ]
}

###

# Requisição válida, porém sem codinome
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"},
        {"url": "https://arc20201.boidacarapreta.cc"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição válida, porém sem url
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"},
        {"codinome": "boi"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição válida COMPLETA
POST https://api.arc20201.boidacarapreta.cc/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"},
        {"codinome": "ederson.torresini"},
        {"url": "https://arc20201.boidacarapreta.cc"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###
