# https://v2.docs.influxdata.com/v2.0/reference/api/

POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "campo": "ideias",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "posicao": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###
