# https://v2.docs.influxdata.com/v2.0/reference/api/

POST {{$processEnv INFLUXDB_BASEURL}}/api/v2/write?org={{$processEnv INFLUXDB_ORG}}&bucket={{$processEnv INFLUXDB_BUCKET}}
Authorization: Token {{$processEnv INFLUXDB_TOKEN}}
Content-Type: application/octet-stream
Accept: application/json

ideia,local=casa,personagem=Lola,ação=brincando latitude=-27.6084177,longitude=-48.6354691,altitude=80

###